name: earkart_omni
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  #utils
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  google_fonts: ^4.0.3
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  permission_handler: ^12.0.0
  path_provider: ^2.1.5
  file_picker: ^10.1.9
  open_filex: ^4.7.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get: ^4.7.2
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  easy_debounce: ^2.0.3
  package_info_plus: any
  device_info_plus: ^11.4.0
  dartz: ^0.10.1

  #ui
  figma_squircle: ^0.6.3
  modal_bottom_sheet: ^3.0.0
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/sounds/
