export const PacketState = {
  PacketType: 2,
  PacketName: "Info",
  Transducers: [
    {
      ID: "8dc59de7-2e27-45cf-8b74-8b5fc09819d4",
      Name: "CAEP8",
      HF: false,
      CalibrationDate: "2025-03-07",
      ConductionType: 0,
      EarSides: [0, 1],
      SignalTypes: [0, 1, 2, 3, 4, 7],
      Rates: [0.5, 1.0, 2.0],
      Calibrations: [
        {
          SignalType: 0,
          CalibrationFrequencies: [
            {
              Frequency: 125,
              MaxLevelHL: 90,
              MinLevelHL: -10,
              Calibration: 36,
            },
            {
              Frequency: 250,
              MaxLevelHL: 105,
              MinLevelHL: -10,
              Calibration: 23,
            },
            {
              Frequency: 500,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 18,
            },
            {
              Frequency: 750,
              MaxLevelHL: 105,
              MinLevelHL: -10,
              Calibration: 19,
            },
            {
              Frequency: 1000,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 15,
            },
            {
              Frequency: 1500,
              MaxLevelHL: 100,
              MinLevelHL: -10,
              Calibration: 22,
            },
            {
              Frequency: 2000,
              MaxLevelHL: 105,
              MinLevelHL: -10,
              Calibration: 20,
            },
            {
              Frequency: 3000,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 18,
            },
            {
              Frequency: 4000,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 21,
            },
            {
              Frequency: 6000,
              MaxLevelHL: 90,
              MinLevelHL: -10,
              Calibration: 30,
            },
            {
              Frequency: 8000,
              MaxLevelHL: 80,
              MinLevelHL: -10,
              Calibration: 42,
            },
          ],
        },
        {
          SignalType: 1,
          CalibrationFrequencies: [
            {
              Frequency: 125,
              MaxLevelHL: 90,
              MinLevelHL: -10,
              Calibration: 36,
            },
            {
              Frequency: 250,
              MaxLevelHL: 105,
              MinLevelHL: -10,
              Calibration: 23,
            },
            {
              Frequency: 500,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 18,
            },
            {
              Frequency: 750,
              MaxLevelHL: 105,
              MinLevelHL: -10,
              Calibration: 19,
            },
            {
              Frequency: 1000,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 15,
            },
            {
              Frequency: 1500,
              MaxLevelHL: 100,
              MinLevelHL: -10,
              Calibration: 22,
            },
            {
              Frequency: 2000,
              MaxLevelHL: 105,
              MinLevelHL: -10,
              Calibration: 20,
            },
            {
              Frequency: 3000,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 18,
            },
            {
              Frequency: 4000,
              MaxLevelHL: 110,
              MinLevelHL: -10,
              Calibration: 21,
            },
            {
              Frequency: 6000,
              MaxLevelHL: 90,
              MinLevelHL: -10,
              Calibration: 30,
            },
            {
              Frequency: 8000,
              MaxLevelHL: 80,
              MinLevelHL: -10,
              Calibration: 42,
            },
          ],
        },
        {
          SignalType: 2,
          CalibrationFrequencies: [
            {
              Frequency: 125,
              MaxLevelHL: 65,
              MinLevelHL: -10,
              Calibration: 68,
            },
            {
              Frequency: 250,
              MaxLevelHL: 80,
              MinLevelHL: -10,
              Calibration: 50,
            },
            {
              Frequency: 500,
              MaxLevelHL: 85,
              MinLevelHL: -10,
              Calibration: 46,
            },
            {
              Frequency: 750,
              MaxLevelHL: 85,
              MinLevelHL: -10,
              Calibration: 43,
            },
            {
              Frequency: 1000,
              MaxLevelHL: 85,
              MinLevelHL: -10,
              Calibration: 40,
            },
            {
              Frequency: 1500,
              MaxLevelHL: 80,
              MinLevelHL: -10,
              Calibration: 46,
            },
            {
              Frequency: 2000,
              MaxLevelHL: 85,
              MinLevelHL: -10,
              Calibration: 43,
            },
            {
              Frequency: 3000,
              MaxLevelHL: 90,
              MinLevelHL: -10,
              Calibration: 39,
            },
            {
              Frequency: 4000,
              MaxLevelHL: 90,
              MinLevelHL: -10,
              Calibration: 39,
            },
            {
              Frequency: 6000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 49,
            },
            {
              Frequency: 8000,
              MaxLevelHL: 75,
              MinLevelHL: -10,
              Calibration: 54,
            },
          ],
        },
        {
          SignalType: 3,
          CalibrationFrequencies: [
            { Frequency: -1, MaxLevelHL: 105, MinLevelHL: 0, Calibration: 21 },
          ],
        },
        {
          SignalType: 4,
          CalibrationFrequencies: [
            { Frequency: -1, MaxLevelHL: 85, MinLevelHL: -10, Calibration: 46 },
          ],
        },
        {
          SignalType: 7,
          CalibrationFrequencies: [
            { Frequency: -1, MaxLevelHL: 80, MinLevelHL: -10, Calibration: 49 },
          ],
        },
      ],
    },
    {
      ID: "a0b4d9cd-66ac-4eb7-a1f9-135804a5bd4c",
      Name: "B71",
      HF: false,
      CalibrationDate: "2025-03-07",
      ConductionType: 1,
      EarSides: [0, 1, 3],
      SignalTypes: [0, 1, 7],
      Rates: [0.5, 1.0, 2.0],
      Calibrations: [
        {
          SignalType: 0,
          CalibrationFrequencies: [
            {
              Frequency: 250,
              MaxLevelHL: 45,
              MinLevelHL: -10,
              Calibration: 76,
            },
            {
              Frequency: 500,
              MaxLevelHL: 65,
              MinLevelHL: -10,
              Calibration: 58,
            },
            {
              Frequency: 750,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 54,
            },
            {
              Frequency: 1000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 49,
            },
            {
              Frequency: 1500,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 43,
            },
            {
              Frequency: 2000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 43,
            },
            {
              Frequency: 3000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 49,
            },
            {
              Frequency: 4000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 47,
            },
            {
              Frequency: 6000,
              MaxLevelHL: 50,
              MinLevelHL: -10,
              Calibration: 73,
            },
            { Frequency: 8000, MaxLevelHL: 0, MinLevelHL: -10, Calibration: 0 },
          ],
        },
        {
          SignalType: 1,
          CalibrationFrequencies: [
            {
              Frequency: 250,
              MaxLevelHL: 45,
              MinLevelHL: -10,
              Calibration: 76,
            },
            {
              Frequency: 500,
              MaxLevelHL: 65,
              MinLevelHL: -10,
              Calibration: 58,
            },
            {
              Frequency: 750,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 54,
            },
            {
              Frequency: 1000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 49,
            },
            {
              Frequency: 1500,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 43,
            },
            {
              Frequency: 2000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 43,
            },
            {
              Frequency: 3000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 49,
            },
            {
              Frequency: 4000,
              MaxLevelHL: 70,
              MinLevelHL: -10,
              Calibration: 47,
            },
            {
              Frequency: 6000,
              MaxLevelHL: 50,
              MinLevelHL: -10,
              Calibration: 73,
            },
            { Frequency: 8000, MaxLevelHL: 0, MinLevelHL: -10, Calibration: 0 },
          ],
        },
        {
          SignalType: 7,
          CalibrationFrequencies: [
            { Frequency: -1, MaxLevelHL: 45, MinLevelHL: -10, Calibration: 76 },
          ],
        },
      ],
    },
  ],
  SpeechMaterial: {
    Languages: [
      {
        Name: "ITALIANO",
        Materials: ["Logotomi", "Bisillabiche", "Pediatriche"],
      },
      {
        Name: "ENGLISH",
        Materials: [
          {
            Name: "MONOSYLLABIC NU 6",
            PhonemeLists: [
              {
                Name: "List 1",
                Phonemes: [
                  "LAUD",
                  "BOAT",
                  "POOL",
                  "NAG",
                  "LIMB",
                  "SHOUT",
                  "SUB",
                  "VINE",
                  "DIME",
                  "GOOSE",
                ],
              },
              { Name: "List 2" },
              { Name: "List 3" },
              { Name: "List 4" },
              { Name: "List 5" },
              { Name: "List 6" },
              { Name: "List 7" },
              { Name: "List 8" },
              { Name: "List 9" },
              { Name: "List 10" },
              { Name: "List 11" },
              { Name: "List 12" },
              { Name: "List 13" },
              { Name: "List 14" },
              { Name: "List 15" },
              { Name: "List 16" },
              { Name: "List 17" },
              { Name: "List 18" },
              { Name: "List 19" },
              { Name: "List 20" },
            ],
          },
          { Name: "SPONDEE  WORDS" },
          { Name: "MONOSYLLABIC CID W-22" },
          { Name: "CHILD  SPONDEE" },
          { Name: "CHILD  PBK-50" },
          { Name: "Maryland  CNC" },
          { Name: "MONOSYLLABIC PB-50" },
        ],
      },
      {
        Name: "FRANCAIS",
        Materials: ["Mots voix femme", "Mots voix homme", "Audiom Enfants"],
      },
      { Name: "DEUTSCH", Materials: ["ZAHLEN", "WORTER"] },
      {
        Name: "ESPANOL",
        Materials: [
          "Palabras trisilabicas",
          "Palabras bisilabicas",
          "Polisilabas",
          "Ponderadas",
          "Frases",
          "NÃºmeros",
        ],
      },
      {
        Name: "NEDERLANDS",
        Materials: ["Volwassen 21-40", "Volwassen 01-20", "Kinder"],
      },
      { Name: "PORTUGUES", Materials: ["MONOSSILBICAS", "DISSLABA"] },
      { Name: "MAGYAR", Materials: ["NONSZENSZ SZAVAK", "SZAMOK"] },
      { Name: "VLAAMS", Materials: ["WORDS"] },
      {
        Name: "TURK",
        Materials: ["UC HECELI KELIMELER", "TEK HECELI KELIMELER"],
      },
      { Name: "ÎÎÎÎÎÎÎÎ", Materials: ["List 1-20", "List 1 and 2"] },
      {
        Name: "RomÃ¢nÄ",
        Materials: [
          "0-3 Fraze",
          "3-5 BisilabicÄ",
          "5-7 BisilabicÄ",
          "7-12 BisilabicÄ",
          "7-12 MonosilabicÄ",
          "12-100 BisilabicÄ",
          "12-100 MonosilabicÄ",
        ],
      },
      {
        Name: "×¢××¨××ª",
        Materials: [
          "MALE ADULTS",
          "MALE CHILDREN",
          "MALE DISC",
          "WOMAN ADULTS",
          "WOMAN CHILDREN",
          "WOMAN DISC",
        ],
      },
    ],
    Selected: {
      Language: { Index: 1, Name: "ENGLISH" },
      Material: { Index: 0, Name: "MONOSYLLABIC NU 6" },
      List: { Index: 0, Name: "List 1" },
      Phoneme: { Index: 0, Name: "LAUD" },
    },
  },
};
